spring.application.name=tickets

# Conexión con la base de datos 
spring.mongodb.uri=mongodb://localhost:27017/db_tickets

# Mostrar comandos en la consola
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

# Creación automatica de índices
spring.data.mongodb.auto-index-creation=true